# docker-compose/docker-compose.infras.yaml
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ../config:/mosquitto/config
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../data/s3:/data
    environment:
      MINIO_ROOT_USER: ccuser
      MINIO_ROOT_PASSWORD: ccpassword
      MINIO_OPTS: "--console-address :9001"
    command: ["server", "/data", "--console-address", ":9001"]
