# docker-compose/docker-compose.plugin.yaml
services:
  cc-plugin:
    build:
      context: ../
      dockerfile: plugin/Dockerfile
    container_name: cc-plugin
    env_file:
      - ../env_files/plugin.local.env
      - ../env_files/ffrd.plugin.local.env
    working_dir: /root
    volumes:
      - ../:/root
      - ../../cc-py-sdk/src/cc:/root/cc
    command: ["python", "plugin/main.py"]
